#!/bin/sh
# athena starting script by rowla
# modified by shazeya@syafi.com (NL101541)
# traduzido por GreenBox e mkbu95

PATH=./:$PATH

L_SRV=login-server_sql
C_SRV=char-server_sql
M_SRV=map-server_sql

print_start() {
echo "Iniciando Cronus-Emulator"
echo "(c) 2003 Athena Project"
echo ""
echo "Realizando verificação..."
}

check_files() {
    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "O arquivo $i não existe."
            echo "Erro: verifique sua compilação."
            exit 1;
        fi
    done

    echo "Verificação finalizada!"
    echo "Iniciando o emulador..."
}
    

case $1 in
    'ligar')
        print_start
        check_files

        exec ./${L_SRV}&
        exec ./${C_SRV}&
        exec ./${M_SRV}&

        echo "Cronus iniciado com sucesso!"
    ;;
    'desligar')
        ps ax | grep -E "${L_SRV}|${C_SRV}|${M_SRV}" | awk '{print $1}' | xargs kill
    ;;
    'reiniciar')
        $0 desligar
        $0 ligar
    ;;
    *)
        echo "Uso: cronus-start { ligar | desligar | reiniciar }"
    ;;
esac
